### PR TITLE
Added support for Auga UI.

### PR DESCRIPTION
**Pull request by maker-dude**
Updated to support the Auga UI plugin

Doesn't currently have trash functionality, otherwise the rest should all work the same.

### CODE REVIEW

**Comment by Goldenrevolver** [comment]
sorry, I don't have notifications for my github. I'm open to review this and talk about it, preferably on discord ( Goldenrevolver#9054 ) if you fine with that. I currently have a lot of local code changes for the rewrite of the chest access system, so those kept me busy

**Comment by maker-dude** [comment]
no worries - i sent you a friend request on Discord - maker_dude

**Comment by maker-dude** [comment]
@Goldenrevolver I've updated my branch based on our conversation.

**Comment by murpii** [comment]
Any update on this?

**Comment by Goldenrevolver** [comment]
> Any update on this?

yes, I added jblaske as a contributor yesterday so it is easier to merge this with my big 1.3 update. jblaske is actively working on merging it whenever possible, but we are all only doing this in our limited free time

**Comment by murpii** [comment]
Great, thanks.

**Comment by maker-dude** [comment]
@Goldenrevolver MUC update merge is complete - go ahead and give it another look when you can.

**Comment by Diagonet** [comment]
This is the only thing stopping me from using Auga, very excited for when it gets approved

**Comment by WitherOfMc** [comment]
Any update on this merge?

**Comment by PalaNolho** [comment]
@Goldenrevolver @jblaske 
Auga had some significant updates recently due to the latest changes in the vanilla UI code.

It would be worth reviewing this pull request in the face of those changes.

**Comment by AyanoKaito** [comment]
Hi, are there any compatibility updates? T_T

**Pull request closed without merging**
